---
name: sawmill

instance_groups:
- name: sawmill
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sawmill
    release: sawmill

- name: smoke-tests
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: smoke-tests
    release: sawmill

properties:
  sawmill:
    users:
    - name: admin-blue
      pass: ((sawmill-blue-password))
    - name: admin-green
      pass: ((sawmill-green-password))
    ssl_crt: ((sawmill-tls.certificate))
    ssl_key: ((sawmill-tls.private_key))
    skip_ssl_verify: true

variables:
- name: sawmill-blue-password
  type: password
- name: sawmill-green-password
  type: password
- name: sawmill-ca
  type: certificate
  options:
    is_ca: true
    common_name: sawmillCA
- name: sawmill-tls
  type: certificate
  options:
    ca: sawmill-ca
    common_name: sawmill
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.sawmill.default.sawmill.bosh"

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: sawmill
  version: 2.1.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/sawmill-boshrelease?v=2.1.0
  sha1: e7f3f8687b907a5f5983a3d5aa0345c663f675db
