---
meta:
  dns_root: (( param "Please configure your root DNS name" ))
  security_groups: (( param "Please configure your AWS Security Groups" ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: sawmill
    networks:
      - name: sawmill1
        static_ips: (( static_ips(0, 1, 2, 3, 4, 5) ))
    persistent_disk: (( grab meta.persistent_disk ))
  - name: smoke-tests
    networks:
      - name: sawmill1

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m3.medium

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: sawmill1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
