---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: sawmill
    templates:
    - name: sawmill
      release: sawmill
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "Please configure the networks for this job" ))
  - name: smoke-tests
    templates:
    - name: smoke-tests
      release: sawmill
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "Please configure the networks for this job" ))
    lifecycle: errand

networks: (( param "Please configure the global network definitions for this Deployment" ))
